### understand pytorch in deep
- [ ] source:https://towardsdatascience.com/understanding-pytorch-with-an-example-a-step-by-step-tutorial-81fc5f8c4e8e
- [x] source:https://www.youtube.com/playlist?list=PLZbbT5o_s2xrfNyHZsM6ufI0iZENK9xgG


#### 


In [6]:


np.random.seed(42)
x = np.random.rand(100,1)
# print(x)
y = 1 + 2 * x + .1 * np.random.randn(100, 1)

#####  environment check: 

In [1]:
import torch
print(torch.__version__)
torch.version.cuda

1.7.1


'11.0'

##### numpy to tensor
* torch.tensor() automatically type matching
* torch.tensor() can manully set data type
* as_tensor and from_numpy share the memory with original data,means only pointer,no memory copy

In [9]:
import numpy as np
data = np.array([1,2,3])

print(type(data),
      torch.Tensor(data),
    torch.tensor(data),
    torch.as_tensor(data),
    torch.from_numpy(data))



<class 'numpy.ndarray'> tensor([1., 2., 3.]) tensor([1, 2, 3], dtype=torch.int32) tensor([1, 2, 3], dtype=torch.int32) tensor([1, 2, 3], dtype=torch.int32)


In [19]:
torch.tensor(data, dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

##### random creating data

In [10]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [11]:
torch.zeros(4,5,7)

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

In [12]:
torch.ones(1,2)

tensor([[1., 1.]])

In [13]:
torch.rand(3,3)

tensor([[0.1079, 0.9675, 0.5851],
        [0.1177, 0.9873, 0.4664],
        [0.7671, 0.7584, 0.0477]])

In [14]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

#### tensor operation
* reshape
* element-wise operation
* dimention reduction/addition 增减维度
* concatinating two tensors
* tensor.stack: add a new dimention(always the batch size)

In [22]:
t = torch.tensor([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
t.size()


torch.Size([4, 4])

In [23]:
t.shape

torch.Size([4, 4])

In [24]:
t.numel()

16

In [27]:
t.reshape(1,-1).squeeze().shape

torch.Size([16])

In [28]:
t.reshape(1,-1).shape

torch.Size([1, 16])

In [30]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[5,6],[7,8]])
torch.cat((t1,t2),dim = 0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [31]:
torch.cat((t1,t2),dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])